name: "PHP_Codesniffer"

on:
    pull_request:
#        paths:
#            - "**.php"
#            - "phpcs.xml.dist"
#            - ".github/workflows/phpcs.yaml"
    push:
#        paths:
#            - "**.php"
#            - "phpcs.xml.dist"
#            - ".github/workflows/phpcs.yaml"

jobs:
    phpcs:
        name: PHP_CodeSniffer
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.2'

            - name: Install dependencies
              run: composer update --prefer-dist --no-progress --ignore-platform-req="ext-*" ${{ matrix.composer-prefer }}

            - name: Run PHP_CodeSniffer
              run: vendor/bin/phpcs
