name: "PHPUnit tests"


on:
    pull_request:
#        paths:
#            - "**.php"
#            - "phpunit.xml.dist"
#            - ".github/workflows/phpunit.yaml"
    push:
#        paths:
#            - "**.php"
#            - "phpunit.xml.dist"
#            - ".github/workflows/phpunit.yaml"

jobs:
    unit-tests:
        name: Unit Tests
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-version:
                    - "8.2"
        steps:
            -   uses: actions/checkout@master

            -   name: Set up PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-versions }}

            -   name: Validate composer.json and composer.lock
                run: composer validate --strict

            -   name: Cache Composer packages
                id: composer-cache
                uses: actions/cache@v2
                with:
                    path: vendor
                    key: ${{ runner.os }}-composer-${{ matrix.composer-prefer }}$-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-composer-${{ matrix.composer-prefer }}-

            -   name: Install dependencies
                run: composer update --prefer-dist --no-progress --ignore-platform-req="ext-*" ${{ matrix.composer-prefer }}

            -   name: Run test suite
                run: vendor/bin/phpunit ${{ matrix.phpunit-flags }}
